version: "3.7"

services: 
  mongodatabase:
    build: ./database
    restart: always
    ports:
      - "2717:27017"
  node-app:
    build: .
    network_mode: "host"
    ports:
      - "4200:4200"
    volumes:
      - usr/app/node_modules
      - .:/usr/app